Week 3/user model custom 실습/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

Week 3/user model custom 실습/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.main, name="main"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
]

Week 3/user model custom 실습/users/models.py
# users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    GENDER_CHOICE = [
        ('Male', '남자'),
        ('Female', '여자'),
    ]
    JOB_CHOICE = [
        ('Student', '학생'),
        ('JobSeeker', '취준생'),
        ('Worker', '직장인'),
        ('Etc', '기타')
    ]
    first_name = None
    last_name = None
    name = models.CharField(max_length=10, null=True)
    email = models.EmailField(null=True) # 이메일을 필수 컬럼으로 재선언
    nickname = models.CharField(max_length=20, null=True)
    birth = models.DateField(null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICE, null=True)
    job = models.CharField(max_length=10, choices=JOB_CHOICE, null=True)
    desc = models.TextField(max_length=100, blank=True, null=True)

Week 3/user model custom 실습/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'name', 'nickname',
                'gender', 'job', 'birth', 'desc']

Week 3/user model custom 실습/users/views.py
from django.shortcuts import render, redirect
from users.forms import SignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth

def main(request):
    return render(request, "users/main.html")


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            #메소드 받고, 페이지 이동      
            return render(request, template_name="users/success.html")
        else:
            #url 호출
            return redirect('users:signup')
    else:
        form = SignupForm()
        context = {
            'form': form,
        }
        return render(request, template_name='users/signup.html', context=context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('users:main')
        else:
            context = {
                'form': form,
            }
            return render(request, template_name='users/login.html', context=context)
    else:
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, template_name='users/login.html', context=context)


def logout(request):
    auth.logout(request)
    return redirect('users:main')

Week 3/user model custom 실습/templates/users/login.html
{% extends 'users/main.html' %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form }}
    <button>Login</button>
</form>
{% endblock content %}

Week 3/user model custom 실습/templates/users/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <li><a href="{% url 'users:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'users:login' %}">Login</a></li>
            <li><a href="{% url 'users:signup' %}">Signup</a></li>
        {% endif %}
        <!--들어오는 칸-->
        {% block content %}
        <!--재사용함을 알림-->
        {% endblock content %}
    </body>
</html>

Week 3/user model custom 실습/templates/users/signup.html
{% extends 'users/main.html' %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SignUp">
</form>
{% endblock content %}