Week 4, 5/Django 중급 실습 (피망마켓 만들기)/server/apps/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns= [
    path("", views.posts_list, name="list"),
    path("posts/create", views.posts_create, name="create"),
    path("posts/<int:pk>", views.posts_retrieve, name="retrieve"),
    path("posts/<int:pk>/update", views.posts_update, name="update"),
    path("posts/<int:pk>/delete", views.posts_delete, name="delete"),
]

Week 4, 5/Django 중급 실습 (피망마켓 만들기)/server/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("server.apps.posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Week 4, 5/Django 중급 실습 (피망마켓 만들기)/server/apps/posts/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length= 50)
    age = models.IntegerField(default=0)

class Post(models.Model):
    title = models.CharField(max_length=64)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post_user")
    content = models.TextField()
    region = models.CharField(max_length=16)
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    photo = models.ImageField(blank=True, upload_to='posts/%Y%m%d')

Week 4, 5/Django 중급 실습 (피망마켓 만들기)/server/apps/posts/views.py
from django.shortcuts import render, redirect
from server.apps.posts.models import Post
from django.http.request import HttpRequest

def posts_list(request:HttpRequest, *args, **kwargs):
    posts = Post.objects.all()
    
    #text = request.GET.get("text")
    #if text:
        #posts = posts.filter(content__contains=text)
    min_price = request.GET.get("min_price")
    max_price = request.GET.get("max_price")
    if min_price and max_price :
        posts = posts.filter(price__range=(min_price, max_price))
        
    return render(request, "posts/posts_list.html", {"posts":posts})

def posts_retrieve(request:HttpRequest, pk, *args, **kwargs):
    post = Post.objects.get(id=pk)
    user_name = post.user.name
    user_age = post.user.age
    user = post.user
    all_post = user.post_user.all()
    context = {
        "post" : post,
        "user_name" : user_name,
        "user_age" : user_age,
        "all_post" : all_post
    }
    return render(request, "posts/posts_retrieve.html", context=context)


def posts_create(request:HttpRequest, *args, **kwargs):
    if request.method == "POST":
        Post.objects.create(
            title=request.POST["title"],
            user=request.POST["user"],
            region=request.POST["region"],
            price=request.POST["price"],
            content=request.POST["content"],
            photo = request.FILES.get('photo'),
        )
        return redirect("/")
    return render(request, "posts/posts_create.html")

def posts_delete(request:HttpRequest, pk, *args, **kwargs):
    if request.method == "POST":
        post = Post.objects.get(id=pk)
        post.delete()
    return redirect("/")

def posts_update(request:HttpRequest, pk, *args, **kwargs):
    post = Post.objects.get(id=pk)
    if request.method == "POST":
        post.title=request.POST["title"]
        post.user=request.POST["user"]
        post.region=request.POST["region"]
        post.price=request.POST["price"]
        post.content=request.POST["content"]
        post.photo=request.FILES.get('photo')
        post.save()
        return redirect(f"/posts/{post.id}")
    return render(request, "posts/posts_update.html", {"post":post})

Week 4, 5/Django 중급 실습 (피망마켓 만들기)/server/apps/posts/templates/posts/posts_create.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>피망마켓 - 게시글 작성</title>
    <link rel="stylesheet" href="{% static 'css/create.css '%}" />
  </head>
  <body>
    <h1>글 작성하기</h1>

    <form action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input name="title" placeholder="게시글 제목" />
      <br />
      <input type="file" name="photo" />
      <br />
      <input name="user" placeholder="작성자" />
      <br />
      <input name="region" placeholder="지역" />
      <br />
      <input name="price" placeholder="가격" type="number" />
      <br />
      <textarea name="content" placeholder="게시글 내용"></textarea>
      <div>
        <input type="submit" , value="저장하기" />
      </div>
    </form>
  </body>
</html>

Week 4, 5/Django 중급 실습 (피망마켓 만들기)/server/apps/posts/templates/posts/posts_list.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>피망마켓 - 게시물 목록</title>
    <link rel="stylesheet" href="{% static 'css/list.css '%}" />
</head>
<body>
    <form action="{% url 'posts:list' %}" method="get">
        <input name="min_price" placeholder="최소가격"/>
        <input name="max_price" placeholder="최대가격"/>
        <input type="submit" value="검색"/>
    </form>

    </hr>
    
    {% for post in posts %}
    <article>
    {% if post.photo %}
        <p>
            <img src="{{ post.photo.url }}"/>
        </p>
    {% endif %}
    <div>
    <p><a href="{% url 'posts:retrieve' post.pk %}">{{post.title}}</a></p>
    <small>{{post.region}}</small>
    <p>{{ post.price }}</p>
    </div>
    </article>
    <hr />
    {% endfor %}

    <a href="{% url 'posts:create' %}">
        <img src="{% static 'image/plus.png' %}">
    </a>
</body>
</html>

Week 4, 5/Django 중급 실습 (피망마켓 만들기)/server/apps/posts/templates/posts/posts_retrieve.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>피망마켓 - 게시글 상세</title>
    <link rel="stylesheet" href="{% static 'css/retrieve.css '%}" />
  </head>
  <body>
    <h1>{{post.title}}</h1>
    {% if post.photo %}
      <p>
        <img src="{{ post.photo.url }}"/>
      </p>
    {% endif %}
    <small>작성자:{{user_name}}</small><br />
    <small>나이:{{user_age}}</small><br />
    <small>지역:{{post.region}}</small><br />
    <small>가격:{{post.price}}</small><br />
    <br />
    <p>{{post.content}}</p>
    <br />
    <small>작성일:{{post.created_at}}</small><br />
    <small>수정일:{{post.updated_at}}</small>
    <br />
  <br />
  <small>이 작성자의 글</small>
  {% for post in all_post %}
  <a class="post" href="{% url 'posts:retrieve' post.id %}">{{ post.title }}</a>
  {% endfor %}
    <hr />
    <div>
      <a href="{% url 'posts:update' post.pk %}">수정하기</a>
    </div>
    <form action="{% url 'posts:delete' post.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" , value="삭제하기" />
    </form>
  </body>
</html>

Week 4, 5/Django 중급 실습 (피망마켓 만들기)/server/apps/posts/templates/posts/posts_update.html
<!DOCTYPE html>
<html lang="ko">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>피망마켓 - 게시글 수정</title>
    <link rel="stylesheet" href="{% static 'css/update.css '%}" />
  </head>
  <body>
    <h1>글 수정하기</h1>

    <form action="{% url 'posts:update' post.pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <input name="title" placeholder="게시글 제목" value="{{post.title}}" />
      <br />
      <input type="file" name="photo" />
      <br />
      <input name="user" placeholder="작성자" value="{{post.user}}" />
      <br />
      <input name="region" placeholder="지역" value="{{post.region}}" />
      <br />
      <input
        name="price"
        placeholder="가격"
        type="number"
        value="{{post.price}}"
      />
      <br />
      <textarea name="content" placeholder="게시글 내용">
{{post.content}}</textarea
      >
      <div>
        <input type="submit" , value="저장하기" />
      </div>
    </form>
  </body>
</html>